# Use an official Python runtime as a base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the publisher script into the container
COPY user_publisher.py .
COPY utilities ./utilities
COPY __init__.py .

# Install any dependencies required by the publisher script
RUN pip install pika requests

# Run the publisher script when the container starts
CMD ["python", "user_publisher.py"]
