
version: "3.8"
services:
  inventree-db:
    image: postgres:13
    container_name: inventree-db
    networks:
      - inventree_network
    expose:
      - ${INVENTREE_DB_PORT:-5433}/tcp
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdb
      - POSTGRES_USER=${INVENTREE_DB_USER}
      - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD}
      - POSTGRES_DB=${INVENTREE_DB_NAME}
    volumes:
      - ${INVENTREE_EXT_VOLUME}:/var/lib/postgresql/data/:z
    restart: unless-stopped
  inventree-cache:
    image: redis:7.0
    container_name: inventree-cache
    depends_on:
      - inventree-db
    networks:
      - inventree_network
    profiles:
      - redis
    env_file:
      - .env
    expose:
      - ${INVENTREE_CACHE_PORT:-6379}
    restart: always
  inventree-server:
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-server
    expose:
      - 8000
    depends_on:
      - inventree-db
    networks:
      - inventree_network
    env_file:
      - .env
    volumes:
      - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
    restart: unless-stopped
  inventree-worker:
    image: inventree/inventree:${INVENTREE_TAG:-stable}
    container_name: inventree-worker
    command: invoke worker
    depends_on:
      - inventree-server
    networks:
      - inventree_network
    env_file:
      - .env
    volumes:
      - ${INVENTREE_EXT_VOLUME}:/home/inventree/data:z
    restart: unless-stopped
  inventree-proxy:
    container_name: inventree-proxy
    image: caddy:alpine
    restart: always
    depends_on:
      - inventree-server
    networks:
      - inventree_network
    ports:
      - ${INVENTREE_WEB_PORT:-880}:80
      - 8443:443
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${INVENTREE_EXT_VOLUME}/static:/var/www/static:z
      - ${INVENTREE_EXT_VOLUME}/media:/var/www/media:z
      - ${INVENTREE_EXT_VOLUME}:/var/log:z
      - ${INVENTREE_EXT_VOLUME}:/data:z
      - ${INVENTREE_EXT_VOLUME}:/config:z
  receiver:
    build: .
    depends_on:
      - inventree-server
    networks:
      - inventree_network
      - my_shared_network
  heartbeat_sender:
    build:
      context: ../
      dockerfile: Docker/Dockerfile.heartbeat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - inventree-db
    networks:
      - my_shared_network
networks:
  inventree_network: null
  my_shared_network:
    external: true
