name: Deploy to DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to DEV
    runs-on: inventory
#    environment: staging
    env:
      SSH_HOST: ${{ secrets.SSH_HOST_DEV }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      WORK_DIR: ${{ secrets.WORK_DIR_DEV }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_KEY_DIR: ${{ secrets.SSH_KEY_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts
          sudo apt-get install sshpass

      - name: Connect to Staging Server and Deploy
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -v -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DEV }} <<'ENDSSH'
          eval "$(ssh-agent -s)"                      # Start the SSH agent
          ssh-add ${{ env.SSH_KEY_DIR }}          # Add your private key to the agent
          cd ${{ env.WORK_DIR }}
          pwd
          ls -la  # Check the directory content
          if [ -d ".git" ]; then
              echo "Git directory exists, proceeding with Git operations..."
              
          else
              echo "Not a Git repository. Exiting."
              exit 1
          fi
          echo "Restarting services..."
          pwd
          cd Inventree
          docker compose build
          docker compose up -d
          ENDSSH
      

      - name: Cleanup
        run: rm -rf ~/.ssh
