#name: Inventree-Project
#
#on:
#  push:
#    branches:
#      - main
#jobs:
#  ssh:
#    steps:
#      - name: Write ssh keys
#        run: |
#          install -m 600 -D /dev/null ~/.ssh/id_rsa
#          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#          ssh-keyscan -H ${{ secrets.SSH_PRIVATE_KEY }} > ~/.ssh/known_hosts
#  running-pull:
#    steps:
#      - name: shh keys
#
#      - name: Checkout code
#        uses: actions/checkout@v2
