
name: Deploy to PROD

on:
  push:
    branches:
      - new-main

jobs:
  deploy:
    name: Deploy to PROD
    runs-on: self-hosted
    env:
      SSH_HOST: ${{ secrets.SSH_HOST_PROD }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      WORK_DIR: ${{ secrets.WORK_DIR_PROD }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_KEY_DIR: ${{ secrets.SSH_KEY_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts
          sudo apt-get install sshpass

      - name: Connect to Production Server and Deploy
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -v -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_PROD }} <<'ENDSSH'
          eval "$(ssh-agent -s)"                      # Start the SSH agent
          ssh-add ${{ env.SSH_KEY_DIR }}              # Add your private key to the agent checking if it does git action 
          cd ${{ env.WORK_DIR }}
          echo "Current directory:" $(pwd)
          echo "Checking directory contents..."
          ls -la

          if [ -d ".git" ]; then
              echo "Git directory exists, proceeding with Git operations..."
              # Add Git operations here, such as git pull or git checkout
          else
              echo "Not a Git repository. Exiting."
              exit 1
          fi
          echo "Restarting services..."
          # Commands to restart your services
          cd Inventree
          # Additional deployment commands can be added here
          ENDSSH
      

      - name: Cleanup
        run: |
          rm -rf ~/.ssh/
